### ISSUE TITLE
Error installing PoodLL filter

### ISSUE THREAD

**Issue by deraadt** [justinhunt/moodle-filter_poodll#7] opened 2015-11-27 01:11 UTC
Hi, Justin.

I encountered an error when installing the PoodLL filter on Moodle 3.0. 

    Notice: Undefined property: stdClass::$filter_poodll_serverport in /var/www/vhosts/prototype.moodle.net/html/pluginsdemo/filter/poodll/poodllinit.php on line 16 Notice: Undefined property: stdClass::$filter_poodll_serverport in /var/www/vhosts/prototype.moodle.net/html/pluginsdemo/filter/poodll/poodllinit.php on line 16 Notice: Undefined property: stdClass::$filter_poodll_servername in /var/www/vhosts/prototype.moodle.net/html/pluginsdemo/filter/poodll/poodllinit.php on line 22 Notice: Undefined property: stdClass::$filter_poodll_serverport in /var/www/vhosts/prototype.moodle.net/html/pluginsdemo/filter/poodll/poodllinit.php on line 22 Notice: Undefined property: stdClass::$filter_poodll_serverid in /var/www/vhosts/prototype.moodle.net/html/pluginsdemo/filter/poodll/poodllinit.php on line 22 

I also wasn't getting any audio from the plugin afterwards. Perhaps this was part of the cause.

PS. Are you working on a non-Flash version?

**Comment by justinhunt** [comment] 2015-11-29 07:51
Yes I am working on a non flash version (slowly). I plan to have a tested and good version of PoodLL for Moodle 3 in about a weeks time. I can't say much about the error right now, till I test it. Though that code has not changed. So its probably a change in Moodle somewhere (filter settings file?) that PoodLL is no longer compatible with.

**Comment by deraadt** [comment] 2015-12-02 04:00
If you need someone to help with testing, I'd be happy to do so.

**Comment by justinhunt** [comment] 2015-12-03 14:43
Thanks Michael. I am working away on it. I am a bit shy of the things you might find if I let you test ...

**Comment by justinhunt** [comment] 2015-12-17 15:21
Michael. The latest PoodLL is ready now.  I refactored the filter to bits. You should use the MOODLE_29+ branch. The issue was probably that Moodle had deprecated the filtersettings.php in favor of settings.php. But PoodLL still hadn't moved.

**Comment by deraadt** [comment] 2015-12-21 02:48
Hi, Justin.

I pulled the latest and switched to the MOODLE_29+ branch, but when I upgraded there was file mssing...

    Warning: require_once(/var/www/vhosts/prototype.moodle.net/html/pluginsdemo/filter/poodll/poodllresourcelib.php): failed to open stream: No such file or directory in /var/www/vhosts/prototype.moodle.net/html/pluginsdemo/repository/poodll/lib.php on line 11 Fatal error: require_once(): Failed opening required '/var/www/vhosts/prototype.moodle.net/html/pluginsdemo/filter/poodll/poodllresourcelib.php' (include_path='/var/www/vhosts/prototype.moodle.net/html/pluginsdemo/lib/zend:/var/www/vhosts/prototype.moodle.net/html/pluginsdemo/lib/pear:.:/usr/share/php:/usr/share/pear') in /var/www/vhosts/prototype.moodle.net/html/pluginsdemo/repository/poodll/lib.php on line 11

**Comment by justinhunt** [comment] 2015-12-21 06:36
Hi Michael

Sorry I haven't  made it as clear as I should have. All of the PoodLL mods
will need an upgrade to their MOODLE_29+ branch. The PoodLL filter changed
significantly and files like poodllresourcelib.php no longer exist.

On Mon, Dec 21, 2015 at 11:48 AM, Michael de Raadt <notifications@github.com

**Comment by deraadt** [comment] 2015-12-22 00:02
Hi, Justin.

Thanks for the additional info. I also updated the Poodll repository and Atto plugin and installation worked fine. I was able to get a registration key and add that.

I'm not getting any audio from the recorder and the whiteboard doesn't appear in the modal when I click the icon in the editor for that.

**Comment by justinhunt** [comment] 2015-12-22 05:54
Wow, its all going wrong! The default whiteboard in the atto editor is
still a bit of an issue. That requires jquery. We used to force the loading
of that if it was not available. But that caused all sorts of problems, so
for now if the theme doesn't load jquery, you need to add it in the
additional html area. I am going to build an AMD wrapper for it, to avoid
all this. But the other, better, option is to set the PoodLL Atto plugin to
use the LiterallyCanvas whiteboard, which does use AMD and jquery. Do that
at : site admin -> plugins -> text editors -> atto html editor- ->poodll
anywhere (atto)

In testing that I found a bad bug that I had not noticed before which might
also have been the cause of your missing audio. So you should do yet
another git pull on the PoodLL filter.

Not withstanding bugs, the main cause of missing audio is flash or browser
(particularly Google Chrome) permissions.

**Comment by deraadt** [comment] 2015-12-23 06:35
Hi, Justin.

I've updated the Poodll filter to the latest. I'm now getting some duplication of the Flash items. I've captured it here... https://db.tt/5z4cx9JX

With the whiteboard settings changed, I do get a whiteboard drawing interface now, but it is a bit messy... https://db.tt/8ZMYMwv3

Also, when I go to insert the drawn image, no image is added to the editor.

I'm still not getting any audio. I updated Flash, but I think that's still where the problem is. The volume meter doesn't budge, regardless of what mic I use.

**Comment by justinhunt** [comment] 2015-12-24 03:30
Hi Michael

Thanks for looking at it. The duplication is likely to be simply "double
filtering." That is when the multi media plugins filter and PoodLL are both
filtering on the same file extension (eg mp4). Moving PoodLL higher in the
list of filters, largely works. But not always. So its best to make sure
only one filter is handling a particular extension. PoodLL allows you to
check / uncheck the extensions it handles on the Poodll filter admin
settings page. Or you could enable / disable multimedia plugins filter and
PoodLL filter at the course level if you needed to juggle the use of the
two filters.


The standard Literally Canvas whiteboard has too many controls really for
use in a popup. Thats why we default to drawingboard. Nevertheless it
should do the insert into textarea correctly. I worked pretty hard on that
over the last week. Can you make sure that you are running on the latest
PoodLL filter version, because it got bumped several times. If its still an
issue, there is likely to be an error in the javascript console related to
it.

[a few hours later] actually I had a small brain wave. I think with the
latest PoodLL Anywhere plugin for Atto that drawingboard.js will work
universally. So perhaps switching back to that is the best option.

 The mic and audio recorder issue is a puzzle. Its almost certainly a
flash/browser/hardware issue. If you can get a picture from the snapshot
camera or video recorder, then its probably not a permissions issue,
because they also wouldn't work. If you right click on the recorder and
choose properties, in the audio settings area do you get any joy out of
fiddling with the volume level there?Or plugging in a different mic, and
changing the mic flash uses?

Justin

**Comment by justinhunt** [comment] 2016-01-07 06:53
I will close this issue now, because the initial problem has been fixed. But if the PoodLL issues continue, let me know. I will be working on it more actively over the next few months ... which I am really looking foward to!

**Closed by justinhunt** 2016-01-07 06:53 UTC
